---
# Copyright © 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

tasks:
  - name: Install Hugo dependencies
    before: brew install hugo
    init: echo "Your version of Hugo is `hugo version`"
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0
ports:
  - port: 1313
    onOpen: open-preview
vscode:
  extensions:
    - rusnasonov.vscode-hugo
    - streetsidesoftware.code-spell-checker-dutch
    - streetsidesoftware.code-spell-checker
