# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

image:
  name: klakegg/hugo:ext-alpine
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo --baseUrl https://caspermeijn.gitlab.io/receptenboek/
  artifacts:
    paths:
      - public
  only:
    - master


reuse:
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
  needs: []
